### ISSUE TITLE
Provide aditional compability with prototype

### ISSUE THREAD

**Issue by viniciuscb** [albertopq/jquery_datepicker#10]
Hello, in my rails app I am using prototype together with jQuery. I call prototype by the $ symbol and jQuery with jQuery. ...

Please provide additional compability just by changing the line 14 in lib/app/helpers/form_helper.rb by

``` javascript
      html += javascript_tag("jQuery(document).ready(function(){$('##{input_tag.get_name_and_id["id"]}').datepicker(#{dp_options.to_json})});")
```

to

``` javascript
      html += javascript_tag("jQuery(document).ready(function(){jQuery('##{input_tag.get_name_and_id["id"]}').datepicker(#{dp_options.to_json})});")
```

Thank you

**Comment by albertopq** [comment]
Ok, I'll add it.

Feel free to fork, add it, check tests and pull request if you don't want to wait :)

Thanks.

**Comment by viniciuscb** [comment]
ok, done, I am very new to GIT and did not notice about this possibility.
It have worked in my project with this only modification.

Thanks, Vinicius

On Tue, Dec 13, 2011 at 9:05 AM, albertopq <
reply@reply.github.com

> wrote:
> 
> Ok, I'll add it.
> 
> Feel free to fork, add it, check tests and pull request if you don't want
> to wait :)
> 
> Thanks.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/albertopq/jquery_datepicker/issues/10#issuecomment-3121657

## 

---

Vinicius Cubas Brand
professor de yoga
+55 (41) 8834-3101
www.vinici.us
www.govardhana.com.br

---

Como voc est respirando AGORA.

........__
....._  \ >_
....(_) /  (_)

**Comment by albertopq** [comment]
Discussing in #12
