### ISSUE TITLE
Two datepickers do not load

### ISSUE THREAD

**Issue by ricburton** [albertopq/jquery_datepicker#14]
<%= form_for(@enquiry) do |f| %>
<%= f.datepicker 'from', :class => "small" %>
<%= f.datepicker 'to', :class => "small" %>
<% end %>

This fails unfortunately :( Would love to fix the issue but not sure how.

**Comment by albertopq** [comment]
Hi @burtonic,

Could you please provide more information? What do you mean with "it fails"? It doesn't show the input?
It shouldn't be a problem to show 2 datepickers, so do you mean that if you remove one, it works?

Thanks!

**Comment by ricburton** [comment]
Hey so basically if I have two date-pickers the first doesn't pop up but
the second does. Can I provide any more information?

Richard

On 19 January 2012 14:15, albertopq <
reply@reply.github.com

**Comment by albertopq** [comment]
Hey,

Which rails and jquery version are you using? If you inspect the elements (with firebug console, or something similar) can you see any javascript error?

I tried the exact same code and it seems to work with both inputs. may be something else in your page is conflicting with the datepicker.

Thanks!
