### ISSUE TITLE
Datetime picker

### ISSUE THREAD

**Issue by petrbela** [albertopq/jquery_datepicker#15]
Are you planning to extend support for picking time together with date, possibly based on https://github.com/trentrichardson/jQuery-Timepicker-Addon, which is an extension of jQuery UI's datepicker? Or do you know if such gem already exists?

**Comment by donapieppo** [comment]
+1

**Comment by neokeeper** [comment]
+1

**Comment by osuka** [comment]
+1

**Comment by nurettin** [comment]
+1

**Comment by albertopq** [comment]
Happy to hear your feedback! :)
