### ISSUE TITLE
:value and :dateFormat interfering with each other

### ISSUE THREAD

**Issue by peterbell215** [albertopq/jquery_datepicker#17]
I am trying to create a Ruby app and wanted to use the jquery_datepicker as part of a form.  My code is:

```
   Date: <%= f.datepicker :booking_date, :value => "18 Mar 2012", :dateFormat => "d M yy", :label => "Date"%>
```

The text field gets initially rendered to:

```
   18 M 2012
```

I have tried it with various months, and it always seems to substitute the month name with the letter 'M'.

Many thanks for your help.
Peter

**Comment by albertopq** [comment]
Hi @peterbell215, just updated the code to handle the format you are using.

Cheers!

**Comment by peterbell215** [comment]
Many thanks.  Much appreciated.  Will give it a try in a couple of days.

Best regards,
Peter.

On Mon, Mar 19, 2012 at 12:05 PM, albertopq <
reply@reply.github.com

**Comment by peterbell215** [comment]
Many thanks.  Your fix works perfectly.

Peter.
