### ISSUE TITLE
datepicker does not pop up

### ISSUE THREAD

**Issue by snex** [albertopq/jquery_datepicker#18]
followed exact instructions on Rails 3.2.2, the input box shows up, but clicking on it does not load the datepicker, and on page load, firebug shows the following error: 

jQuery("#user_birthday").datepicker is not a function
http://192.168.1.146:3000/
Line 57

application.js has the following:

//= require jquery
//= require jquery_ujs
//= require jquery-ui
//= require dygraph-combined
//= require_tree .

view looks like this:

<%= datepicker_input "user","birthday" %>

**Comment by albertopq** [comment]
HI @snex,

Could you please paste the source code (html rendered by the browser, I mean) when you get that error into a gist (https://gist.github.com/) ?

Thanks!

**Comment by giorgenes** [comment]
Seems the problem is caused by the fact rails is loading javascript at the end of the document, so jQuery isn't available the time it;s called.

It would be nicer if this used unobstrusive js

**Comment by giorgenes** [comment]
Actually, it was my layout loading at the end. my bad :)

**Comment by albertopq** [comment]
No problem!

Happy to help :)
