### ISSUE TITLE
datepicker doesn't pop up in Chrome (Rails 3.2.2)

### ISSUE THREAD

**Issue by letstalk** [albertopq/jquery_datepicker#20]
Has anyone had this problem so far? It pops up in IE 9 and Firefox 12 but not in Chrome ( 18.0.1025.168 m )

**Comment by albertopq** [comment]
Hi @letstalk 

Is working fine for me in Chrome (same version). Any messages on the console? Any other js that could be breaking it before the datepicker code is executed?

Thanks!

**Comment by letstalk** [comment]
Hi @albertopq,

1 script error: 

Uncaught SyntaxError: Unexpected token }    in   assets/jquery-ui.js?body=1:28

Any ideas?

Thanks!

**Comment by albertopq** [comment]
Not easy, without checking the code...
It seems that your jquery-ui.js file is somehow broken. Try to download it again from http://jqueryui.com/download

I'm going to close the issue, as I don't think is datepicker related. Are you ok with that?

Thanks!

**Comment by letstalk** [comment]
Check again on my other dev environment (mac) and it works. Something's wrong on my side. Sorry for raising issue.
