### ISSUE TITLE
no stylesheet

### ISSUE THREAD

**Issue by penchiang** [albertopq/jquery_datepicker#21]
I tried your gem and it worked quite well for the regular and the nested forms. However, there is no stylesheet. So, the datepicker does not look good. What stylesheet should be used?

**Comment by albertopq** [comment]
Hi @penchiang ,

I've no added styles intentionally, so you can add your own one.
Probably the easiest way is using the one themes provided by jQuery UI. You can download it on:

http://jqueryui.com/download

Let me know if you have any problems installing it.

Regards!
