### ISSUE TITLE
When using nested attributes, id != name

### ISSUE THREAD

**Issue by kb1ibt** [albertopq/jquery_datepicker#3]
When the javascript is being generated if you are using nested attributes instead of getting the id it is getting the name.  o in my case the generated javascript shows $("#registered_user[product_attributes][0]_purchase_date").datepicker(); which doesn't find anything, instead it needs to be $("#registered_user_product_attributes_0_purchase_date").datepicker();

**Comment by kb1ibt** [comment]
I added a fix to my patch-1 (ea7a01bcbd7a96c997cb365a32487c27f51042fd) branch however it has what I would consider crappy regex, if someone has a more elegant solution use it.

**Comment by kb1ibt** [comment]
Closing this issue since I submitted a pull request for this issue. See Issue #4

**Comment by triemstr** [comment]
+1
