### ISSUE TITLE
Passing in options specific to datepicker not working?

### ISSUE THREAD

**Issue by triemstr** [albertopq/jquery_datepicker#5]
Hi, I love this gem.

However, I can't seem to get options to work.  Here is my example line:

```
<%= f.datepicker 'availability', :minDate => -20, :maxDate => "+1M +10D", :tab_index => 70 %>
```

Note I have two types of options here...those that go to datepicker (minDate, maxDate) and those that don't (tab_index).  All are put into the html and minDate and maxDate are not added to datepicker.  I was just trying to do something like this:

http://jqueryui.com/demos/datepicker/

Click 'view source' about halfway down the page and it will show this:

```
<script>
    $(function() {
        $( "#datepicker" ).datepicker({ minDate: -20, maxDate: "+1M +10D" });
    });
</script>
```

The old gem I used to use was calendar_date_select which used prototype.  See the form helpers for that gem here:

https://github.com/timcharper/calendar_date_select/blob/master/lib/calendar_date_select/form_helpers.rb

I think there is a method in the private section called calendar_date_select_process_options that is what is needed here...but correct me if I'm wrong and don't know what I'm doing here.

Thoughts?

Thanks,
Kevin

**Comment by albertopq** [comment]
Good point. I'm not taking in account datepicker options yet.

I'll try to improve it ASAP to make it work.

Thanks for the feedback!

**Comment by albertopq** [comment]
Please, check out the new version.
Let me know any problem.

Cheers.

**Comment by triemstr** [comment]
It works great.  GREAT!  Thank you for the unbelievable response time.

Time to promote this gem some more.  Where can we do it?  I think I found it in a forum somewhere where you posted.  

Also, it would be helpful to add an example with options to the README under 'Usage'.

Thanks albertopq!!

**Comment by albertopq** [comment]
Thanks for your feedback Kevin

I think you mean this question in stackoverflow:

http://stackoverflow.com/questions/3329381/how-do-i-connect-jquery-datepicker-to-my-ruby-on-rails-form

One option to promote this is to vote my answer as the best one. It will putsh up my answer and make it easier to find.

I've posted in a couple of places more:

As a comment here http://www.justinbritten.com/work/2008/06/inline-jquery-datepicker-and-rails/ (first Google option)
In this old wiki http://oldwiki.rubyonrails.org/rails/pages/DatePicker (but still appears in Google)

I'll work on a better documentation, i promise :)

Cheers.

Alberto.

**Comment by triemstr** [comment]
I didn't have reputation on stackoverflow so I posted an answer that mentions you and provided an example.
