### ISSUE TITLE
Initial format of date is incorrect...

### ISSUE THREAD

**Issue by digitalmoksha** [albertopq/jquery_datepicker#7]
Hi,

When the datepicker initializes, and the text form field has a value, that value is initially displayed in the UTC format, such as "2012-03-23 00:00:00 UTC".  Even though I set the dateFormat option when initializing the date picker. 

```
<%= f.datepicker(:expire_on, :minDate => '0y', :maxDate => '5y', 
   :showOn => "both",
   :buttonImage => "/plugin_assets/dm_hanuman/images/icon_calendar.gif",
   :buttonImageOnly => true,
   :showOtherMonths => true,
   :gotoCurrent => true,
   :dateFormat => 'MM d, yy', :changeMonth => true,
   :changeYear => true) %>
```

Am I missing something obvious?

**Comment by albertopq** [comment]
Hi,

I think jQuery Datepicker :dateFormat param works only for the input data that is going to be entered.
If you choose a different date, what format does it take?

Anyway, that's a cool thing to be added (to apply the format sent by the "dateFormat" param to the current value), and make sense with the Rails integration, so I'll add it soon.

Thanks for your feedback!

**Comment by digitalmoksha** [comment]
When I choose the date, it ends up in the correct format.  It's just the initial value from the Rails model that is not initially formatted correctly.  That would a great thing to add - thanks for taking a look at it.

**Comment by albertopq** [comment]
After review it, I'm not sure that this feature must be handled by the helper.

The main problem is that I don't know in what format is going to arribe the date. It depends on which value have you assigned in the controller.

I think the best option is to format it yourself and send it through the :value parameter:

```
<%= f.datepicker(:expire_on, :minDate => '0y', :maxDate => '5y',
     :value => @model.att.strftime('%Y-%m-%d'),
     :showOn => "both",
     :buttonImage => "/plugin_assets/dm_hanuman/images/icon_calendar.gif",
     :buttonImageOnly => true,
     :showOtherMonths => true,
     :gotoCurrent => true,
     :dateFormat => 'MM d, yy', :changeMonth => true,
     :changeYear => true) %>
```

What do you think?

**Comment by digitalmoksha** [comment]
Hmm...I understand what you're saying.  But since this is a rails plugin, and the dates in the database are almost always stored in a standard way, it seems like for 95% of the date fields, you're going to want the current data displayed the same as the date format.  I mean, the initial display should be the same as what the datepciker is going to initially display.

Maybe there is an additional option indicating to format the field initially based on the dateFormat option.

I know for myself, my jquery/javascript fu is not good enough yet to set it properly initially.  I was surprised that the jquery picker didn't actually do it.

So my vote is to include it ;-)

**Comment by albertopq** [comment]
@digitalmoksha, have you tested the new version?
Can I close this issue?

Thanks!

**Comment by digitalmoksha** [comment]
Yes, it looks good.  Thank you for the changes.  Maybe you can also add 

"MM" => "%B", "M" => "%b"

to the format list?
