### ISSUE TITLE
Problem setting the default date

### ISSUE THREAD

**Issue by maxniko** [albertopq/jquery_datepicker#9]
Hi. I'm using your gem and I'm having a hard time getting the textbox generated (with the datepicker_input tag) to display a specific date (say, the current date) on load. I tried using the :defaultDate option but got no results.
Here's the code:

<%= datepicker_input(:busqueda, :fecha_fin, :firstDay => 0, :dateFormat => 'dd/mm/yy', :prevText => 'Anterior', :nextText => 'Siguiente', :maxDate => '+0d', :monthNames => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'], :dayNamesMin => ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa']) %>

I hope to get through this :)
Thanks in advance

**Comment by maxniko** [comment]
Sorry, that's the old code. This is the one I'm using (with no results still):

<%= datepicker_input(:busqueda, :fecha_fin, :firstDay => 0, :dateFormat => 'dd/mm/yy', :prevText => 'Anterior', :nextText => 'Siguiente', :maxDate => '+0d', :monthNames => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'], :dayNamesMin => ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'], :currentText => 'Hoy', :showButtonPanel => true, :closeText => 'Listo', :defaultDate => Time.now) %>

**Comment by albertopq** [comment]
Hi @maxniko,

There are 2 types of parameters in the datepicker_input method:
- For the textfield 
- For the jquery plugin

Setting the initial value is the one that is in both sides, but only is handled by the textfield.

So, what you have to do is send the initial value in the :value parameter as a String like this:

<%= datepicker_input(:busqueda, :fecha_fin, :firstDay => 0, :dateFormat => 'dd/mm/yy', :prevText => 'Anterior', :nextText => 'Siguiente', :maxDate => '+0d', :monthNames => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'], :dayNamesMin => ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'], :currentText => 'Hoy', :showButtonPanel => true, :closeText => 'Listo', _:value => Time.now.utc.to_s_) %>

Let me know if it works for you.

Thanks!

**Comment by albertopq** [comment]
@maxniko , can I close this Issue?

Thanks!

**Comment by maxniko** [comment]
Sorry I took too long. I ended up using jQuery instead of the gem. You may close the issue. :)

**Comment by albertopq** [comment]
Thanks!
